### ISSUE TITLE
'privateKey' not in code from ssh connection

### ISSUE THREAD

**Issue by rigroch** [SusonJohn/redis-ssh2#1]
in function, [async function connect(sshConfig, redisConfig)] not use 'privateKey' parameter. it use only password.

**Comment by SusonJohn** [comment]
> in function, [async function connect(sshConfig, redisConfig)] not use 'privateKey' parameter. it use only password.

ok,I support this way later,please wait

**Comment by rigroch** [comment]
Thank you!

**Comment by SusonJohn** [comment]
> in function, [async function connect(sshConfig, redisConfig)] not use 'privateKey' parameter. it use only password.

[fixed](https://github.com/SusonJohn/redis-ssh2/releases/tag/v1.0.3)
